# Server Port
server.port=8080

# PostgreSQL Connection
# Əgər DB_URL tapılmasa, default olaraq localhost-a qoşulacaq
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/nexacrm_db}
spring.datasource.username=${DB_USERNAME:postgres}
# Parolu boş qoyuruq ki, GitHub-a düşməsin. Lokalda özümüz təyin edəcəyik.
spring.datasource.password=${DB_PASSWORD:}

# JPA / Hibernate Properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT Secret (Bura mütləq gizli qalmalıdır)
app.jwt.secret=${JWT_SECRET}